- LICENSE
> Create LICENSE using MIT

- package.json
- packages/eslint-config-wantedly/__tests__/__snapshots__/index.test.js.snap
- packages/eslint-config-wantedly/index.js
- packages/frolint/__tests__/index.test.js
- packages/frolint/package.json
- packages/frolint/preCommitHook.js
Add test for `frolint` package.
> Test for frolint package

- packages/eslint-config-wantedly-typescript/__tests__/__snapshots__/index.test.js.snap
- packages/eslint-config-wantedly-typescript/index.js
Some ESLint rules are not good for us.
> Update ESLint rules

- packages/frolint/package.json
- yarn.lock
Upgrade `@yamadayuki/ogh` package. This change includes blow:
- Check the current directory is `git` repository when you install or uninstall
- Treat the deleted file properly
> Upgrade ogh package

- packages/eslint-config-wantedly-typescript/__tests__/__snapshots__/index.test.js.snap
- packages/eslint-config-wantedly-typescript/index.js
- packages/eslint-config-wantedly/__tests__/__snapshots__/index.test.js.snap
- packages/eslint-config-wantedly/index.js
- packages/frolint/base.js
- packages/frolint/defaultImplementation.js
- packages/frolint/package.json
- yarn.lock
If you use `frolint` in no react application, this package shows many warnings around eslint-plugin-react.
> Set react version automatically

- packages/eslint-config-wantedly-typescript/without-react.js
- packages/frolint/.prettierrc
- packages/frolint/README.md
- packages/frolint/__tests__/git.test.js
- packages/frolint/base.js
- packages/frolint/config.js
- packages/frolint/defaultImplementation.js
- packages/frolint/package.json
- yarn.lock
Integrate with Prettier.
```
Format ESLint auto-fixable errors -> Apply prettier formatter
```
> Integrate prettier formatter

- packages/frolint/base.js
The `prettier.format` function returns the formatted output whether the output has no diff or not. So check the input and output equality.
> Check the output has diff

- .eslintrc
- lerna.json
- packages/eslint-config-wantedly-typescript/fixtures/@typescript-eslint/no-floating-promises/index.ts
- packages/eslint-config-wantedly-typescript/package.json
- packages/eslint-config-wantedly/package.json
- packages/eslint-plugin-use-macros/package.json
- packages/frolint/base.js
- packages/frolint/defaultImplementation.js
- packages/frolint/package.json
- tsconfig.json
Specify the `parserOption` field when the project is typescript or the project uses `eslint-config-wantedly-typescript`
> Improve specifying the parserOption

- .scaffdog/eslint-plugin-wantedly-rule.md
- package.json
- yarn.lock
Introduce [scaffdog](https://github.com/cats-oss/scaffdog) to create new rules.
> Introduce scaffdog

- packages/eslint-plugin-wantedly/rules/__tests__/nexus-pascal-case-type-name.test.js
- packages/eslint-plugin-wantedly/rules/__tests__/nexus-type-description.test.js
- packages/eslint-plugin-wantedly/rules/nexus-pascal-case-type-name.js
- packages/eslint-plugin-wantedly/rules/nexus-type-description.js
> Tweak lint error messages

- packages/eslint-config-wantedly-typescript/.npmignore
- packages/eslint-config-wantedly/.npmignore
- packages/eslint-plugin-use-macros/.npmignore
- packages/eslint-plugin-wantedly/.npmignore
- packages/frolint/.npmignore
- packages/prettier-config-wantedly/.npmignore
https://www.npmjs.com/package/eslint-config-wantedly-typescript
🤔
> Add .npmignore to reduce unpacked size

- packages/eslint-plugin-wantedly/rules/nexus-field-description.js
> Fix lint error node to locate the report

- packages/frolint/src/utils/prettier.ts
- yarn.lock
I add the `TSX` in the supported languages.
> Add TSX into supportedLanguages to format `.tsx` file

- packages/eslint-plugin-wantedly/rules/nexus-camel-case-field-name.js
> Check the existence

- yarn.lock
Upgrade devDependencies dependencies to latest.
> Invoke yarn upgrade

- packages/frolint/src/commands/PrintConfigCommand.ts
- packages/frolint/src/index.ts
Enable to print ESLint config for specific file.
```
$ frolint print-config src/index.ts
```
> Introduce print-config subcommand

- packages/frolint/src/index.ts
> Do not depend on package.json

- packages/eslint-plugin-wantedly/docs/rules/nexus-camel-case-field-name.md
- packages/eslint-plugin-wantedly/docs/rules/nexus-enum-values-description.md
- packages/eslint-plugin-wantedly/docs/rules/nexus-field-description.md
- packages/eslint-plugin-wantedly/docs/rules/nexus-pascal-case-type-name.md
- packages/eslint-plugin-wantedly/docs/rules/nexus-type-description.md
- packages/eslint-plugin-wantedly/docs/rules/nexus-upper-case-enum-members.md
- packages/eslint-plugin-wantedly/src/rules/__tests__/nexus-camel-case-field-name.test.ts
- packages/eslint-plugin-wantedly/src/rules/__tests__/nexus-enum-values-description.test.ts
- packages/eslint-plugin-wantedly/src/rules/__tests__/nexus-field-description.test.ts
- packages/eslint-plugin-wantedly/src/rules/__tests__/nexus-pascal-case-type-name.test.ts
- packages/eslint-plugin-wantedly/src/rules/__tests__/nexus-type-description.test.ts
- packages/eslint-plugin-wantedly/src/rules/__tests__/nexus-upper-case-enum-members.test.ts
- packages/eslint-plugin-wantedly/src/rules/nexus-camel-case-field-name.ts
- packages/eslint-plugin-wantedly/src/rules/nexus-enum-values-description.ts
- packages/eslint-plugin-wantedly/src/rules/nexus-field-description.ts
- packages/eslint-plugin-wantedly/src/rules/nexus-pascal-case-type-name.ts
- packages/eslint-plugin-wantedly/src/rules/nexus-type-description.ts
- packages/eslint-plugin-wantedly/src/rules/nexus-upper-case-enum-members.ts
- packages/eslint-plugin-wantedly/src/rules/utils.ts
> Fix import source which is renamed from `nexus` to `@nexus/schema`

- packages/eslint-plugin-wantedly/package.json
> Relax peerDependencies to eslint and graphql

- package.json
- packages/eslint-config-wantedly-typescript/__tests__/__snapshots__/index.test.js.snap
- packages/eslint-config-wantedly-typescript/__tests__/__snapshots__/without-react.test.js.snap
- packages/eslint-config-wantedly-typescript/package.json
- packages/eslint-config-wantedly-typescript/without-react.js
- packages/eslint-config-wantedly/__tests__/__snapshots__/index.test.js.snap
- packages/eslint-config-wantedly/__tests__/__snapshots__/without-react.test.js.snap
- packages/eslint-plugin-wantedly/package.json
- packages/eslint-plugin-wantedly/src/__tests__/__snapshots__/index.test.ts.snap
- packages/frolint/package.json
- yarn.lock
Use TypeScript v5.
Use jest and ts-jest v29.
> build(deps-dev): Bump TypeScript to v5

- .github/workflows/labeler.yml
> Revert "Bump actions/labeler from 3 to 5"

- .github/workflows/labeler.yml
> ci: Bump actions/labeler to v4
